config/routes.rb
ManP::Application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

   resources :users

  root to: 'users#new'
    get 'manfriends', to: 'users#manfriends', as: 'manfriends'
  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/destroy'

  resources :relationship
  resources :posts

end

app/models/Relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id, :follower_id

  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

end

app/models/manpost.rb
class Post < ActiveRecord::Base
  default_scope order: 'createdat DESC'
  attr_accessible :content, :userid
  belongs_to :user

  validates :content, length: { maximum: 200 }
end

app/models/user.rb
class User < ActiveRecord::Base
def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save!
  end
end
end

has_many :posts

=begin
has_many :followers, through: :follower_relationships
has_many :followeds, through: :followed_relationships

def following? user
  self.followed.include? user
end
def follow user
  Relationship.create follower_id: self.id, followed_id: user.id
end
     =end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  protect_from_forgery with: :exception

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  # For APIs, you may want to use :null_session instead.

end

app/controllers/manfriends_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    if current_user
      redirect_to manfriends_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'Thank you for signing up to Man Points'
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @post = Post.new
    @relationship = Relationship.where(
        follower_id: current_user.id,
        followed_id: @user.id
    ).first_or_initialize if current_user
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def buddies
    if current_user
      @post = Post.new
      manfriends_ids = current_user.followeds.map(&:id).push(current_user.id)
      @post = Ribbit.find_all_by_user_id manfriends_ids
    else
      redirect_to root_url
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @post = Post.new(params[:post])
    @post.user_id = current_user.id
    if @post.save
      redirect_to current_user
    else
      flash[:error] = 'Problem!'
      redirect_to current_user
    end
  end

  def index
    @posts = Post.all include: :user
    @post = Post.new
  end
end

app/controllers/relationship_controller.rb
class RelationshipsController < ApplicationController
  def create
    @relationship = Relationship.new
    @relationship.followed_id = params[:followed_id]
    @relationship.follower_id = current_user.id
    if @relationship.save
      redirect_to User.find params[:followed_id]
    else
      flash[:error] = "Couldn't Follow"
      redirect_to root_url
    end
  end

  def destroy
    @relationship = Relationship.find(params[:id])
    @relationship.destroy
    redirect_to user_path params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url, notice: 'Logged in!'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet/less" href="/style.less">
    <script src="/less.js"></script>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header>
    <div class="wrapper">
                <a href='<%= root_url %>'><img src="/gfx/logo.png"></a>
        <span>Twitter Clone</span>
        <% if current_user %>
            <%= link_to "Buddies' Ribbits", buddies_path %>
            <%= link_to "Public Profiles", users_path %>
            <%= link_to "My Profile", current_user %>
            <%= link_to "Public Ribbits", postss_path %>
        <% end %>

    </div>
    </header>


  <div class="wrapper">
<div id="user_nav">
    <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>!
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
    <% else %>
        <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
    <% end %>
</div>
      <div id="content">
    <% flash.each do |name,msg| %>
        <% content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
<%= yield %>
</div>
   </div>

    <footer>
        <div class="wrapper">
           A Twitter Clone Tutorial <img src="/gfx/logo-nettuts.png">
        </div>
    </footer>

</body>
</html>

app/views/posts/index.html.erb
<% if current_user %>
    <div id="createPost" class="panel right">
        <h1>Do something manly?</h1>
        <p>
            <%= form_for @post do |f| %>
                <%= f.text_area :content, class: 'manText' %>
                <%= f.submit "Click" %>
            <% end %>
        </p>
    </div>
<% end %>
<div class="panel left">
    <h1>Manly Events</h1>
    <% @posts.each do |post| %>
        <div class="manWrapper">
            <a href="<%= user_path post.user %>">
       #         <img class="avatar" src="<%= post.user.avatar_url %>">
                <span class="name"><%= post.user.name %></span>
            </a>
            @<%= post.user.username %>
            <span class="time"><%= time_ago_in_words(post.created_at) %></span>
            <p> <%= post.content %> </p>
        </div>
    <% end %>
</div>